language : node_js
node_js :
  - "0.12"
#before_deploy:
deploy :
   provider : openshift
   user : rosito.susana@gmail.com
   password : vacaciones123 # puede ser encriptado
   domain : developsu
   app : 
	develop : vacacionespermanentes



